<?php

namespace AutoBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @param integer $currentPage
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getAllCars($currentPage = 1) {
        $query = $this->createQueryBuilder('c')->orderBy('c.createdAt', 'DESC')->getQuery();
        $paginator = $this->paginate($query, $currentPage);
        return $paginator;
    }

    /**
     * Paginator Helper
     *
     * @param \Doctrine\ORM\Query $dql   DQL Query Object
     * @param integer            $page  Current page (defaults to 1)
     * @param integer            $limit The total number per page (defaults to 5)
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($dql, $page = 1, $limit = 6)
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }
}
